force-app/main/default/objects/Case/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
                <isActive>false</isActive>
                <label>Invalid</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Intakes</relationshipLabel>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allegany</fullName>
            </value>
            <value>
                <fullName>Anne Arundel</fullName>
            </value>
            <value>
                <fullName>Baltimore City</fullName>
            </value>
            <value>
                <fullName>Baltimore County</fullName>
            </value>
            <value>
                <fullName>Calvert</fullName>
            </value>
            <value>
                <fullName>Caroline</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cecil</fullName>
            </value>
            <value>
                <fullName>Charles</fullName>
            </value>
            <value>
                <fullName>Dorchester</fullName>
            </value>
            <value>
                <fullName>Frederick</fullName>
            </value>
            <value>
                <fullName>Garrett</fullName>
            </value>
            <value>
                <fullName>Harford</fullName>
            </value>
            <value>
                <fullName>Howard</fullName>
            </value>
            <value>
                <fullName>Kent</fullName>
            </value>
            <value>
                <fullName>Montgomery</fullName>
            </value>
            <value>
                <fullName>OTHS</fullName>
            </value>
            <value>
                <fullName>Out of State</fullName>
            </value>
            <value>
                <fullName>Prince George&apos;s</fullName>
            </value>
            <value>
                <fullName>Queen Anne&apos;s</fullName>
            </value>
            <value>
                <fullName>Somerset</fullName>
            </value>
            <value>
                <fullName>St. Mary&apos;s</fullName>
            </value>
            <value>
                <fullName>Talbot</fullName>
            </value>
            <value>
                <fullName>Washington</fullName>
            </value>
            <value>
                <fullName>Wicomico</fullName>
            </value>
            <value>
                <fullName>Worcester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Intake.recordType-meta.xml
<RecordType>
    <fullName>Intake</fullName>
    <active>true</active>
    <businessProcess>Intake</businessProcess>
    <label>Intake_</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Invaild</fullName>
                <isActive>false</isActive>
                <label>Invaild</label>
            </value>
            <value>
                <fullName>LGBTQ</fullName>
                <isActive>false</isActive>
                <label>LGBTQ</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Person_Role__c.field-meta.xml
<CustomField>
    <fullName>Intake_Person_Role__c</fullName>
    <label>Person Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoptive Parent</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Alleged Maltreator</fullName>
            </value>
            <value>
                <fullName>Alleged Victim</fullName>
            </value>
            <value>
                <fullName>Biological Child</fullName>
            </value>
            <value>
                <fullName>Biological Parent</fullName>
            </value>
            <value>
                <fullName>CASA Worker</fullName>
            </value>
            <value>
                <fullName>Casehead</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Child Day Care Provider</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Court Therapist</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc.- Requestor</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc. - Subject</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Enhanced Aftercare Recipient</fullName>
            </value>
            <value>
                <fullName>Foster Parent</fullName>
            </value>
            <value>
                <fullName>Friend/Neighbor</fullName>
            </value>
            <value>
                <fullName>I &amp; R Participant</fullName>
            </value>
            <value>
                <fullName>Law Enforcement</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Legal Representive</fullName>
            </value>
            <value>
                <fullName>Medical Professional</fullName>
            </value>
            <value>
                <fullName>Mental Health Professional</fullName>
            </value>
            <value>
                <fullName>Non-Victim Child</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Adult</fullName>
            </value>
            <value>
                <fullName>Other Adult (Not in Household)</fullName>
            </value>
            <value>
                <fullName>Other Child</fullName>
            </value>
            <value>
                <fullName>Other Child (Not in Household)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/JURISDICTION__c.field-meta.xml
<CustomField>
    <fullName>JURISDICTION__c</fullName>
    <label>JURISDICTION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Washington</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State_Id_Drivers_License__c.field-meta.xml
<CustomField>
    <fullName>State_Id_Drivers_License__c</fullName>
    <label>State Id/Drivers License</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Number_of_days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days__c</fullName>
    <formula>TODAY() - DATEVALUE (CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Reopen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PersonSearchController.cls
public with sharing class PersonSearchController {
    
    @AuraEnabled
    public static String getContacts(String searchJSON) {
        
        if(String.isNotBlank(searchJSON)) {
            
            List<Contact> contactList = new List<Contact> ();
            SearchInputWrapper inputWrap = (SearchInputWrapper) JSON.deserialize(searchJSON, SearchInputWrapper.class);
            Date personDOB = inputWrap.dob;
            
            FieldLevelSecurity.checkFieldAccessByCriteria('Name, FirstName, LastName, Casevault_PID__c, SSN__c, Date_of_Birth__c, Gender__c,Intake_Person_Role__c,'
                                                          +'State_Id_Drivers_License__c, Intake__c, Investigation__c, Service_Case__c', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));
            
            
            String contactJSON = 'SELECT Id, Name, Casevault_PID__c, SSN__c,Date_of_Birth__c, Gender__c, State_Id_Drivers_License__c,Intake_Person_Role__c, Intake__c, Investigation__c, Service_Case__c FROM Contact'; 
            contactJSON += ' WHERE LastName != null';

            if( String.isNotBlank(inputWrap.firstName) ) {

                contactJSON +=  ' AND FirstName LIKE \''+ String.escapeSingleQuotes(inputWrap.firstName) +'%'+'\'';
            }
            if( String.isNotBlank(inputWrap.lastName) ) {

                contactJSON +=  ' AND LastName LIKE \''+ String.escapeSingleQuotes(inputWrap.lastName) +'%'+'\'';
            }
            if( inputWrap.dob != NULL ) {

                contactJSON +=  ' AND Date_of_Birth__c = :personDOB';
            }
            if( String.isNotBlank(inputWrap.casevaultPid) ) {

                contactJSON +=  ' AND Casevault_PID__c LIKE \''+ String.escapeSingleQuotes(inputWrap.casevaultPid) +'%'+'\'';
            }
            if( String.isNotBlank(inputWrap.ssn) ) {
                contactJSON +=  ' AND SSN__c LIKE \''+ String.escapeSingleQuotes(inputWrap.ssn) +'%'+'\'';
            }
            if( String.isNotBlank(inputWrap.dlNo) ) {

                contactJSON +=  ' AND State_Id_Drivers_License__c LIKE \''+ String.escapeSingleQuotes(inputWrap.dlNo) +'%'+'\'';
            }
            contactJSON +=' LIMIT 500 ';

            contactList = Database.query(contactJSON);
            
            return JSON.serialize(contactList);
            
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static String personsIntakeInvSC(String selectedPersonJSON) {
       
        if(String.isNotBlank(selectedPersonJSON)) {

            Contact selectedPerson = (Contact)JSON.deserialize(selectedPersonJSON, Contact.class);
            PersonsWrapper wrapperIns = new PersonsWrapper();
            if(String.isNotBlank(selectedPerson.Intake__c)) {

                FieldLevelSecurity.checkFieldAccessByCriteria('CaseNumber, Origin, Jurisdiction__c', 'view', 'Case',  Boolean.valueOf(Label.HasNamespace));
                wrapperIns.intake = [SELECT Id, CaseNumber, Origin, Jurisdiction__c FROM Case WHERE Id = :selectedPerson.Intake__c]; 
            }
            if(String.isNotBlank(selectedPerson.Investigation__c)) {

                FieldLevelSecurity.checkFieldAccessByCriteria('Name, CPS_Response_Type__c', 'view', 'Investigation__c',  Boolean.valueOf(Label.HasNamespace));
                wrapperIns.investigation = [SELECT Id, Name, CPS_Response_Type__c FROM Investigation__c WHERE Id = :selectedPerson.Investigation__c];
            }
            if(String.isNotBlank(selectedPerson.Service_Case__c)) {

                FieldLevelSecurity.checkFieldAccessByCriteria('Name, Status__c, Number_of_days__c', 'view', 'Service_Case__c',  Boolean.valueOf(Label.HasNamespace));
                wrapperIns.serviceCase = [SELECT Id, Name, Status__c, Number_of_days__c FROM Service_Case__c WHERE Id = :selectedPerson.Service_Case__c];
            }
            return JSON.serialize(wrapperIns);
        } else {
            return null;
        }
    }
    
    public class SearchInputWrapper {
        
        public String firstName; 
        public String lastName;
        public Date dob;
        public String ssn;
        public String casevaultPid;
        public String dlNo;       
    }

    public class PersonsWrapper {

        public Case intake;
        public Investigation__c investigation;
        public Service_Case__c serviceCase;
    }
}