force-app/main/default/objects/Case/fields/Head_of_Household__c.field-meta.xml
<CustomField>
    <fullName>Head_of_Household__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Head of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Intakes</relationshipLabel>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_days_created_date__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_created_date__c</fullName>
    <formula>TODAY() - DATEVALUE (CreatedDate)</formula>
    <label>Number of days created date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Restrict_UnRestrict__c.field-meta.xml
<CustomField>
    <fullName>Restrict_UnRestrict__c</fullName>
    <label>Restrict/UnRestrict</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UnRestricted</fullName>
                <default>true</default>
                <label>UnRestricted</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Supervisor_Approver__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Casevault Supervisor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_Removal__c/Child_Removal__c.object-meta.xml
<CustomObject>
    <label>Child Removal</label>
    <nameField>
        <displayFormat>Child Removal- {0000000}</displayFormat>
        <label>Child Removal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Removals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_Removal__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Child Removals</relationshipLabel>
    <relationshipName>Child_Removals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/HEAD_OF_HOUSEHOLD__c.field-meta.xml
<CustomField>
    <fullName>HEAD_OF_HOUSEHOLD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Head Of Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Due_On__c.field-meta.xml
<CustomField>
    <fullName>Due_On__c</fullName>
    <formula>CreatedDate  + 59</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Head_of_Household__c.field-meta.xml
<CustomField>
    <fullName>Head_of_Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Head of Household</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Number_of_days_created_date__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_created_date__c</fullName>
    <formula>IF(TODAY() &lt;  Due_On__c , Due_On__c -TODAY() , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of days created date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Response_Timer__c.field-meta.xml
<CustomField>
    <fullName>Response_Timer__c</fullName>
    <label>Response Timer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Investigation_Findings__c/Investigation_Findings__c.object-meta.xml
<CustomObject>
    <label>Investigation Findings</label>
    <nameField>
        <displayFormat>IF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigation Findings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation_Findings__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Investigation Findings</relationshipLabel>
    <relationshipName>Investigation_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation_Findings__c/fields/Supervisor_Approver__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Casevault Supervisor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Investigation_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvestigationController.cls
public  with sharing class InvestigationController {
    
    @AuraEnabled
    public static String getInvestigationRecord(Id investigationId, String objectApiName) {
        
        getInitialWrapper intiWrapper = new getInitialWrapper();
        
        if(String.isNotBlank(investigationId)) {
            
            if(objectApiName == 'Child_Removal__c') {
                investigationId = [SELECT Id, Investigation__c FROM Child_Removal__c WHERE Id = :investigationId LIMIT :Utility.queryLimit].Investigation__c;
            }

            FieldLevelSecurity.checkFieldAccessByCriteria('Intake__c, Number_of_days_created_date__c,Due_On__c, Head_of_Household__c, Response_Timer__c', 'view', 'Investigation__c',  Boolean.valueOf(Label.HasNamespace));
            FieldLevelSecurity.checkFieldAccessByCriteria('Restrict_UnRestrict__c, Origin, CaseNumber, Supervisor_Approver__c,Status', 'view', 'Case',  Boolean.valueOf(Label.HasNamespace));
            FieldLevelSecurity.checkFieldAccessByCriteria('Casevault_PID__c, Name', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));

            intiWrapper.investigationRecord = [SELECT Id,Name, Intake__c, Intake__r.CaseNumber, Due_On__c,Intake__r.Supervisor_Approver__r.Name, 
                                               Intake__r.Restrict_UnRestrict__c, Head_of_Household__r.Name, Head_of_Household__r.Casevault_PID__c, Response_Timer__c,
                                               Intake__r.Origin, CreatedDate, Number_of_days_created_date__c, Owner.Name, Intake__r.Status 
                                               FROM Investigation__c 
                                               WHERE Id =: investigationId LIMIT :Utility.queryLimit
                                              ];
            
            Datetime createddate = intiWrapper.investigationRecord.CreatedDate;
            intiWrapper.startDate = createddate.format('MM/dd/yyyy hh:mm a');
            if (String.isNotBlank(intiWrapper.investigationRecord.Intake__c)) {
            List<Case> intakeReviewerDetails = [SELECT Id, Owner.Name FROM Case 
                                                              WHERE Id=:intiWrapper.investigationRecord.Intake__c LIMIT :Utility.queryLimit];
            if(intakeReviewerDetails != Null && intakeReviewerDetails.size() > 0) {
                intiWrapper.reviewer = intakeReviewerDetails[0].Owner.Name;
            }
           }
            
            FieldLevelSecurity.checkFieldAccessByCriteria('Investigation__c, Approval_Status__c, Supervisor_Approver__c', 'view', 'Investigation_Findings__c',  Boolean.valueOf(Label.HasNamespace));
            
            List<Investigation_Findings__c> invenstigationFindingRec = [SELECT Id, Investigation__c, Approval_Status__c, Supervisor_Approver__r.Name 
                                                                        FROM Investigation_Findings__c WHERE Investigation__c = :investigationId 
                                                                        ORDER BY LastModifiedDate DESC LIMIT 1];
            
            
            return JSON.serialize(intiWrapper);
            
        } else {
            
            return null;
            
        }
        
        
    }
    
    public class getInitialWrapper { 
        @AuraEnabled
        public Investigation__c investigationRecord;
        @AuraEnabled
        public String startDate;
        @AuraEnabled
        public String reviewer; 
        
    }
}