force-app/main/default/objects/Child_Removal__c/Child_Removal__c.object-meta.xml
<CustomObject>
    <label>Child Removal</label>
    <nameField>
        <displayFormat>Child Removal- {0000000}</displayFormat>
        <label>Child Removal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Removals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_Removal__c/fields/Autism_Personal_Hygiene__c.field-meta.xml
<CustomField>
    <fullName>Autism_Personal_Hygiene__c</fullName>
    <label>Autism Personal Hygiene</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bathes Self</fullName>
            </value>
            <value>
                <fullName>Dresses Self</fullName>
            </value>
            <value>
                <fullName>Fixes Hair</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Brushing Teeth</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Washes Hair</fullName>
            </value>
            <value>
                <fullName>Menstruation</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Bathing Self</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Dressing Self</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Fixing Hair</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Removing Clothes</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Using the Toilet</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Washing and Drying Hands</fullName>
            </value>
            <value>
                <fullName>Needs Assistance with Washing Hair</fullName>
            </value>
            <value>
                <fullName>Toilet Alone</fullName>
            </value>
            <value>
                <fullName>Toilet Trained</fullName>
            </value>
            <value>
                <fullName>Washes and Dries Hands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child_Removal__c/fields/Autism_Special_Needs__c.field-meta.xml
<CustomField>
    <fullName>Autism_Special_Needs__c</fullName>
    <label>Autism Special Needs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Age is &gt; 6</fullName>
            </value>
            <value>
                <fullName>Emotional Disability</fullName>
            </value>
            <value>
                <fullName>High Risk of Physical or Mental Disease</fullName>
            </value>
            <value>
                <fullName>Mentally Retarded</fullName>
            </value>
            <value>
                <fullName>Other Disability</fullName>
            </value>
            <value>
                <fullName>Physical Disability</fullName>
            </value>
            <value>
                <fullName>Racial or Ethnic Factor</fullName>
            </value>
            <value>
                <fullName>Sibling Group</fullName>
            </value>
            <value>
                <fullName>Feeding Tube</fullName>
            </value>
            <value>
                <fullName>Hearing Disability</fullName>
            </value>
            <value>
                <fullName>Learning Disability</fullName>
            </value>
            <value>
                <fullName>Visual Disability</fullName>
            </value>
            <value>
                <fullName>Developmentally Delayed</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
            <value>
                <fullName>Apnea Monitor</fullName>
            </value>
            <value>
                <fullName>Car Safety Seat</fullName>
            </value>
            <value>
                <fullName>Crutches / Cane / Walker</fullName>
            </value>
            <value>
                <fullName>Deaf</fullName>
            </value>
            <value>
                <fullName>Language Interpreter Required</fullName>
            </value>
            <value>
                <fullName>Hearing Disability / Hearing Aid (Left)</fullName>
            </value>
            <value>
                <fullName>Hearing Disability / Hearing Aid (Right)</fullName>
            </value>
            <value>
                <fullName>Glasses / Contacts</fullName>
            </value>
            <value>
                <fullName>Nightmares</fullName>
            </value>
            <value>
                <fullName>Orthopedic Appliance</fullName>
            </value>
            <value>
                <fullName>Physical Disability / Requires Wheelchair</fullName>
            </value>
            <value>
                <fullName>Special Diet (Specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child_Removal__c/fields/Removal_Type__c.field-meta.xml
<CustomField>
    <fullName>Removal_Type__c</fullName>
    <label>Removal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Judicial Determination</fullName>
            </value>
            <value>
                <fullName>Children with Disabilities Voluntary Placement</fullName>
            </value>
            <value>
                <fullName>Time Limited Voluntary Placement</fullName>
            </value>
            <value>
                <fullName>Enhanced Aftercare Voluntary Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChildRemovalController_Test.cls
@isTest
private class ChildRemovalController_Test {

    @isTest static void testgetInitialInfoAndUpdateChildRemoval() {
        
        Child_Removal__c childRemovalRec = new Child_Removal__c();
        childRemovalRec.Autism_Personal_Hygiene__c = 'Bathes Self';
        childRemovalRec.Autism_Special_Needs__c = 'Age is > 6';
        insert childRemovalRec;
        
        ChildRemovalController.getInitialWrapper childRemovalWrapperRec = (ChildRemovalController.getInitialWrapper)JSON.deserialize(ChildRemovalController.getInitialInfo(childRemovalRec.Id), ChildRemovalController.getInitialWrapper.class);
        System.assertEquals(childRemovalWrapperRec.childRemovalRecord, childRemovalRec);
        
        childRemovalRec.Removal_Type__c = 'Judicial Determination'; 
        ChildRemovalController.updateChildRemoval(JSON.serialize(childRemovalRec));  
        
        Child_Removal__c childRemovalTestRecord = [SELECT Id, Removal_Type__c FROM Child_Removal__c LIMIT 1];
        system.assertEquals(childRemovalTestRecord.Removal_Type__c == 'Judicial Determination', true);
        
        
    }
}