force-app/main/default/objects/Casevault_Unique_Id__c/Casevault_Unique_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Casevault Unique Id</label>
</CustomObject>

force-app/main/default/objects/Casevault_Unique_Id__c/fields/Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Auto_Number__c</fullName>
    <label>Auto Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Approval__c.field-meta.xml
<CustomField>
    <fullName>Home_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Approval</label>
    <referenceTo>Home_Approval__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Home_Approval__c/Home_Approval__c.object-meta.xml
<CustomObject>
    <label>Home Approval</label>
    <nameField>
        <displayFormat>Home-{00000}</displayFormat>
        <label>Home Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Approval__c/fields/Home_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Approval_Status__c</fullName>
    <label>Home Approval Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
public class ContactTriggerHandler {

    public static void onBeforeInsert(List<Contact> contacts) {
        
        Set<Id> homeApprovalIds = new Set<Id>();
   		Map<Id, Contact> conHomeApprovalMap = new Map<Id, Contact>(); 
        
        Casevault_Unique_Id__c  cvUniqueLstSettingIns = Casevault_Unique_Id__c.getValues('Person');
        Decimal casevaultPIDValue = 0;
        if (cvUniqueLstSettingIns == null) {
            cvUniqueLstSettingIns = new Casevault_Unique_Id__c( Name = 'Person');
        } else {
            casevaultPIDValue = cvUniqueLstSettingIns.Auto_Number__c ;
        }
        
        for(Contact con : contacts) {
            
            if(con.Home_Approval__c != null) {
                
               homeApprovalIds.add(con.Home_Approval__c);
               conHomeApprovalMap.put(con.Home_Approval__c, con);                 
            }
                
            casevaultPIDValue++;
            con.Casevault_PID__c = 'PE-'+Integer.valueOf(casevaultPIDValue);            
        } 
        
        cvUniqueLstSettingIns.Auto_Number__c = casevaultPIDValue;
    	upsert cvUniqueLstSettingIns;
        
        FieldLevelSecurity.checkFieldAccessByCriteria('Home_Approval_Status__c,','view','Home_Approval__c', Boolean.valueOf(Label.HasNamespace));
        for(Home_Approval__c home : [SELECT Id, Home_Approval_Status__c FROM Home_Approval__c WHERE Id IN :homeApprovalIds 
                                AND Home_Approval_Status__c = 'Approved']) {
            
            if(conHomeApprovalMap != null && conHomeApprovalMap.containsKey(home.Id) && conHomeApprovalMap.get(home.Id) != null) {
                
                Contact con = conHomeApprovalMap.get(home.Id);
                
                if(con != null) {
                    con.addError('Not allowed to create or change the value once approved the home approval.');
                }             
            }
        }
    }
    
    public static void onBeforeUpdate(List<Contact> contacts) {

		Set<Id> homeApprovalIds = new Set<Id>();
   		Map<Id, Contact> conHomeApprovalMap = new Map<Id, Contact>();        
        for(Contact con : contacts) {
            
            if(con.Home_Approval__c != null) {
                
               homeApprovalIds.add(con.Home_Approval__c);
               conHomeApprovalMap.put(con.Home_Approval__c, con);                 
            }                                 
        } 
        FieldLevelSecurity.checkFieldAccessByCriteria('Home_Approval_Status__c,','view','Home_Approval__c', Boolean.valueOf(Label.HasNamespace));
        for(Home_Approval__c home : [SELECT Id, Home_Approval_Status__c FROM Home_Approval__c WHERE Id IN :homeApprovalIds 
                                AND Home_Approval_Status__c = 'Approved']) {
            
            if(conHomeApprovalMap != null && conHomeApprovalMap.containsKey(home.Id) && conHomeApprovalMap.get(home.Id) != null) {
                
                Contact con = conHomeApprovalMap.get(home.Id);
                
                if(con != null) {
                    con.addError('Not allowed to create or change the value once approved the home approval.');
                }             
            }
        }
    }
}