force-app/main/default/objects/Contact/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>IllinoisIndiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>MontanaNebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
            <value>
                <fullName>New Mexico</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Address_ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Date_of_Birth__c  ) ) ,
  IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/County_Address__c.field-meta.xml
<CustomField>
    <fullName>County_Address__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allegany</fullName>
                <default>true</default>
                <label>Allegany</label>
            </value>
            <value>
                <fullName>Anne Arundel</fullName>
            </value>
            <value>
                <fullName>Baltimore City</fullName>
            </value>
            <value>
                <fullName>Baltimore County</fullName>
            </value>
            <value>
                <fullName>Calvert</fullName>
            </value>
            <value>
                <fullName>Caroline</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cecil</fullName>
            </value>
            <value>
                <fullName>Charles</fullName>
            </value>
            <value>
                <fullName>Dorchester</fullName>
            </value>
            <value>
                <fullName>Frederick</fullName>
            </value>
            <value>
                <fullName>Garrett</fullName>
            </value>
            <value>
                <fullName>Harford</fullName>
            </value>
            <value>
                <fullName>Howard</fullName>
            </value>
            <value>
                <fullName>Kent</fullName>
            </value>
            <value>
                <fullName>Montgomery</fullName>
            </value>
            <value>
                <fullName>Prince George&apos;s</fullName>
            </value>
            <value>
                <fullName>Queen Anne&apos;s</fullName>
            </value>
            <value>
                <fullName>Somerset</fullName>
            </value>
            <value>
                <fullName>St. Mary&apos;s</fullName>
            </value>
            <value>
                <fullName>Talbot</fullName>
            </value>
            <value>
                <fullName>Washington</fullName>
            </value>
            <value>
                <fullName>Wicomico</fullName>
            </value>
            <value>
                <fullName>Worcester</fullName>
            </value>
            <value>
                <fullName>Out of State</fullName>
            </value>
            <value>
                <fullName>OTHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Invaild</fullName>
                <isActive>false</isActive>
                <label>Invaild</label>
            </value>
            <value>
                <fullName>LGBTQ</fullName>
                <isActive>false</isActive>
                <label>LGBTQ</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Approval__c.field-meta.xml
<CustomField>
    <fullName>Home_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Approval</label>
    <referenceTo>Home_Approval__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State_Id_Drivers_License__c.field-meta.xml
<CustomField>
    <fullName>State_Id_Drivers_License__c</fullName>
    <label>State Id/Drivers License</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Approval__c/Home_Approval__c.object-meta.xml
<CustomObject>
    <label>Home Approval</label>
    <nameField>
        <displayFormat>Home-{00000}</displayFormat>
        <label>Home Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Approval__c/fields/Home_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Home_Approval_Status__c</fullName>
    <label>Home Approval Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FindingPersonController.cls
public  with sharing class FindingPersonController {

    @AuraEnabled
    public static String getInitialInformation() {
        GetInitialWrapper initWrap = new GetInitialWrapper();
        initwrap.genderPicklist =  Utility.getPicklistinfo('Contact','Gender__c',false);
        initwrap.statePicklist =  Utility.getPicklistinfo('Contact','Address_State__c',false);
        initwrap.countryPicklist =  Utility.getPicklistinfo('Contact','County_Address__c',false);
        return JSON.serialize(initWrap);
    }
    @AuraEnabled
    public static String getPersons(String searchJSON) {
        if(String.isNotBlank(searchJSON)){
            SearchInputWrapper inputWrap = (SearchInputWrapper) JSON.deserialize(searchJSON, SearchInputWrapper.class);
            List<contact> contactList = new List<contact> ();
            FieldLevelSecurity.checkFieldAccessByCriteria(' Name, FirstName, LastName, Casevault_PID__c, SSN__c, Date_of_Birth__c, Gender__c, Age__c,'+
            'Address_Line_1__c , Address_Line_2__c, Address_ZipCode__c, Address_State__c, County_Address__c, Address_City__c', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));
            String contactJSON = 'SELECT Id, Name, FirstName, LastName, Casevault_PID__c, SSN__c, Date_of_Birth__c, Gender__c, Age__c, '; 
            contactJSON += 'Address_Line_1__c , Address_Line_2__c, Address_ZipCode__c, Address_State__c, County_Address__c, Address_City__c FROM Contact';
            contactJSON += ' WHERE LastName != null AND Home_Approval__r.Home_Approval_Status__c != \'Approved\' AND Service_Case__c = NULL AND Intake__c = NULL AND Investigation__c = NULL';
            Date DOB = inputWrap.dob;
            Decimal age = inputWrap.approxAge;
            if(String.isNotBlank(inputWrap.firstName)){
                contactJSON +=  ' AND FirstName LIKE \''+ String.escapeSingleQuotes(inputWrap.firstName) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.lastName)){
                contactJSON +=  ' AND LastName LIKE \''+ String.escapeSingleQuotes(inputWrap.lastName) +'%'+'\'';
            }
            if(inputWrap.dob != Null){
                contactJSON +=  ' AND Date_of_Birth__c =:DOB';
            }
            if(String.isNotBlank(inputWrap.casevaultPId)){
                contactJSON +=  ' AND Casevault_PID__c LIKE \''+ String.escapeSingleQuotes(inputWrap.casevaultPId) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.ssn)){
                contactJSON +=  ' AND SSN__c LIKE \''+ String.escapeSingleQuotes(inputWrap.ssn) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.stateId)){
                contactJSON +=  ' AND State_Id_Drivers_License__c LIKE \''+ String.escapeSingleQuotes(inputWrap.stateId) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.gender)) {
                contactJSON +=  ' AND Gender__c  LIKE \''+ String.escapeSingleQuotes(inputWrap.gender) +'%'+'\'';
            }
            if(inputWrap.approxAge != Null){
                contactJSON += ' AND Age__c	=:age';
            }
            if(String.isNotBlank(inputWrap.addLine1)){
                contactJSON += ' AND Address_Line_1__c LIKE	\''+ String.escapeSingleQuotes(inputWrap.addLine1) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.addLine2)){
                contactJSON += ' AND Address_Line_2__c LIKE	\''+ String.escapeSingleQuotes(inputWrap.addLine2) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.zipCode)){
                contactJSON += ' AND Address_ZipCode__c LIKE \''+ String.escapeSingleQuotes(inputWrap.zipCode) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.state)){
                contactJSON += ' AND Address_State__c LIKE \''+ String.escapeSingleQuotes(inputWrap.state) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.city)){
                contactJSON += ' AND Address_City__c LIKE \''+ String.escapeSingleQuotes(inputWrap.city) +'%'+'\'';
            }
            if(String.isNotBlank(inputWrap.country)){
                contactJSON += ' AND County_Address__c  LIKE\''+ String.escapeSingleQuotes(inputWrap.country) +'%'+'\'';            
            }
            Integer queryLimit = Utility.queryLimit;
            contactJSON +=' LIMIT :queryLimit ';
            contactList = Database.query(contactJSON);
            inputWrap.contactList = contactList;
            return JSON.serialize(inputWrap.contactList);
        }else{
            return null;
        }
    }
    
    @AuraEnabled
    public static String updatePerson(String contactJSON) {
       
        if (String.isNotBlank(contactJSON)) {
            Contact updatePerson = (Contact) JSON.deserialize(contactJSON, Contact.class);
            if (String.isNotBlank(updatePerson.Id)) {
                FieldLevelSecurity.checkFieldAccessByCriteria('Service_Case__c,Intake__c,Investigation__c', 'update', 'Contact',  Boolean.valueOf(Label.HasNamespace));
                update updatePerson;
            } 
        return updatePerson.Id;
        } else {
            return null;
        }
    }
    public class SearchInputWrapper {
        
        Public String firstName; 
        Public String ssn;
        Public String middleName;
        Public String lastName;
        Public String stateId;
        Public String aliasName;
        Public Date dob;
        Public String fein;
        Public String socialMediaName;
        Public Decimal approxAge;
        Public String gender;
        Public String complaint;
        Public String addLine1;
        Public String addLine2;
        Public String email;
        Public String casevaultPId;
        Public String cisId;
        Public String phone;
        Public String mdmId;
        Public String zipCode;
        Public String state;
        Public String occupation;
        Public String petition;
        Public String city;
        Public String country;
        Public String old;
        @AuraEnabled
        public List<Contact> contactList;
    }
     public class GetInitialWrapper {
        @AuraEnabled
        public List<Utility.pickListWrap> genderPicklist;
        @AuraEnabled
        public List<Utility.pickListWrap> statePicklist;
         @AuraEnabled
        public List<Utility.pickListWrap> countryPicklist;
     }
}