force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Date_of_Birth__c  ) ) ,
  IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Invaild</fullName>
                <isActive>false</isActive>
                <label>Invaild</label>
            </value>
            <value>
                <fullName>LGBTQ</fullName>
                <isActive>false</isActive>
                <label>LGBTQ</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>Is_Caregiver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Caregiver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Is_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>Is_Caregiver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Caregiver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships (Person)</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Person_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Person_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Related To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships (Person Related To)</relationshipLabel>
    <relationshipName>Relationships2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Values__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Values__c</fullName>
    <label>Relationship Values</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoptive Mother</fullName>
            </value>
            <value>
                <fullName>Biological Brother</fullName>
            </value>
            <value>
                <fullName>Biological Child</fullName>
            </value>
            <value>
                <fullName>Biological Father</fullName>
            </value>
            <value>
                <fullName>Biological Mother</fullName>
            </value>
            <value>
                <fullName>Biological Sister</fullName>
            </value>
            <value>
                <fullName>Boyfriend</fullName>
            </value>
            <value>
                <fullName>Boyfriend-Ex</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Child care centre employee</fullName>
            </value>
            <value>
                <fullName>Child care home provider</fullName>
            </value>
            <value>
                <fullName>Child care worker</fullName>
            </value>
            <value>
                <fullName>Child Therapeutic Foster</fullName>
            </value>
            <value>
                <fullName>Co-Worker</fullName>
            </value>
            <value>
                <fullName>Custodian(Legal)</fullName>
            </value>
            <value>
                <fullName>Daughter in Law</fullName>
            </value>
            <value>
                <fullName>Daycare Child.</fullName>
            </value>
            <value>
                <fullName>Father-in-law</fullName>
            </value>
            <value>
                <fullName>Father Therapeutic Foster</fullName>
            </value>
            <value>
                <fullName>Foster Child</fullName>
            </value>
            <value>
                <fullName>Foster Father</fullName>
            </value>
            <value>
                <fullName>Foster Mother</fullName>
            </value>
            <value>
                <fullName>Foster Parent</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Girlfriend</fullName>
            </value>
            <value>
                <fullName>Girlfriend-Ex</fullName>
            </value>
            <value>
                <fullName>GodFather</fullName>
            </value>
            <value>
                <fullName>GodMother</fullName>
            </value>
            <value>
                <fullName>Guardian (Legal)</fullName>
            </value>
            <value>
                <fullName>Half Brother</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelationshipController.cls
public with sharing class RelationshipController {
    
    @AuraEnabled
    public static String getAllPersons(String recordId) {
        
        getInitialWrapper initWrap = new getInitialWrapper ();
        initWrap.relationshipPicklist = Utility.getPicklistinfo('Relationship__c','Relationship_Values__c',false);
        FieldLevelSecurity.checkFieldAccessByCriteria('Name, Age__c,Gender__c,Is_Caregiver__c,Date_of_Birth__c, Casevault_PID__c', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));
        initWrap.contactList = [SELECT Id, Name, Age__c,Gender__c,Is_Caregiver__c,Date_of_Birth__c, Casevault_PID__c  FROM Contact WHERE Service_Case__c = :recordId OR Intake__c =:recordId OR Investigation__c =:recordId LIMIT :Utility.queryLimit];
        
        return JSON.serialize(initWrap);
    }
    
    @AuraEnabled
    public static String getRelationRecord(String personId) {
        
        if(String.isNotBlank(personId)) {
            FieldLevelSecurity.checkFieldAccessByCriteria('Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c', 'view', 'Relationship__c',  Boolean.valueOf(Label.HasNamespace));
            List<Relationship__c> relationships = [SELECT Id,Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c FROM Relationship__c WHERE Person__c = :personId LIMIT :Utility.queryLimit];
        	return JSON.serialize(relationships);
        } else {
            return null;
        }
    }
    
    @AuraEnabled
    public static String saveRelationship(String relationshipJSON) {
        
        if (String.isNotBlank(relationshipJSON)) {
            Relationship__c relationship = (Relationship__c)JSON.deserialize(relationshipJSON,Relationship__c.class);
                FieldLevelSecurity.checkFieldAccessByCriteria('Is_Caregiver__c', 'update', 'Contact',  Boolean.valueOf(Label.HasNamespace));
                Contact contactRecord = new Contact();
                contactRecord.Is_Caregiver__c = relationship.Is_Caregiver__c;
                contactRecord.Id = relationship.Person_Related_To__c;
                update contactRecord;
            if (String.isBlank(relationship.Id)) {
                FieldLevelSecurity.checkFieldAccessByCriteria('Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c', 'create', 'Relationship__c',  Boolean.valueOf(Label.HasNamespace));
                insert relationship;
            } else {
                FieldLevelSecurity.checkFieldAccessByCriteria('Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c', 'update', 'Relationship__c',  Boolean.valueOf(Label.HasNamespace));
                update relationship;
            }
          return relationship.Id;
       } else {
        return null;
       }
        
    }

    public class getInitialWrapper { 
    	
        @AuraEnabled
        public List<Utility.pickListWrap> relationshipPicklist;
        @AuraEnabled
        public List<Contact> contactList;
        
    }
}