force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Date_of_Birth__c  ) ) ,
  IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Person_Role__c.field-meta.xml
<CustomField>
    <fullName>Intake_Person_Role__c</fullName>
    <label>Person Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoptive Parent</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Alleged Maltreator</fullName>
            </value>
            <value>
                <fullName>Alleged Victim</fullName>
            </value>
            <value>
                <fullName>Biological Child</fullName>
            </value>
            <value>
                <fullName>Biological Parent</fullName>
            </value>
            <value>
                <fullName>CASA Worker</fullName>
            </value>
            <value>
                <fullName>Casehead</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Child Day Care Provider</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Court Therapist</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc.- Requestor</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc. - Subject</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Enhanced Aftercare Recipient</fullName>
            </value>
            <value>
                <fullName>Foster Parent</fullName>
            </value>
            <value>
                <fullName>Friend/Neighbor</fullName>
            </value>
            <value>
                <fullName>I &amp; R Participant</fullName>
            </value>
            <value>
                <fullName>Law Enforcement</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Legal Representive</fullName>
            </value>
            <value>
                <fullName>Medical Professional</fullName>
            </value>
            <value>
                <fullName>Mental Health Professional</fullName>
            </value>
            <value>
                <fullName>Non-Victim Child</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Adult</fullName>
            </value>
            <value>
                <fullName>Other Adult (Not in Household)</fullName>
            </value>
            <value>
                <fullName>Other Child</fullName>
            </value>
            <value>
                <fullName>Other Child (Not in Household)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Persons</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/Permanency_Plan__c.object-meta.xml
<CustomObject>
    <label>Permanency Plan</label>
    <nameField>
        <label>Permanency Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permanency Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permanency_Plan__c/fields/Concurrent_Comments__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Concurrent_Permanency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Permanency_Plan__c</fullName>
    <label>Concurrent Permanency Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoption by a non-relative</fullName>
                <default>true</default>
                <label>Adoption by a non-relative</label>
            </value>
            <value>
                <fullName>Adoption by a relative</fullName>
            </value>
            <value>
                <fullName>APPLA</fullName>
            </value>
            <value>
                <fullName>Guardianship by a non-relative</fullName>
            </value>
            <value>
                <fullName>Guardianship by a relative</fullName>
            </value>
            <value>
                <fullName>Reunification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Court_order_received_and_upload_in_CJAMS__c.field-meta.xml
<CustomField>
    <fullName>Court_order_received_and_upload_in_CJAMS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Court order received and uploaded in Casevault</inlineHelpText>
    <label>Court order received&amp;upload in Casevault</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/End_Reason__c.field-meta.xml
<CustomField>
    <fullName>End_Reason__c</fullName>
    <label>End Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Explanation_Required__c.field-meta.xml
<CustomField>
    <fullName>Explanation_Required__c</fullName>
    <label>Explanation Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Guardianship_Planing__c.field-meta.xml
<CustomField>
    <fullName>Guardianship_Planing__c</fullName>
    <label>Guardianship Planing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>APPLICATION</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>DISCLOSURE CHECKLIST</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AGREEMENT</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>ANNUAL REVIEWS</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>SUSPENSION</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>COMPLETED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/If_the_Permanency_plan_is_to_return_home__c.field-meta.xml
<CustomField>
    <fullName>If_the_Permanency_plan_is_to_return_home__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the Permanency plan is to return home or relative placement, is the placement in close proximity to the child&apos;s family?</inlineHelpText>
    <label>If the Permanency plan is to return home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Permanency Plans</relationshipLabel>
    <relationshipName>Permanency_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Plan_Comments__c.field-meta.xml
<CustomField>
    <fullName>Plan_Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Primary_Permanency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Primary_Permanency_Plan__c</fullName>
    <label>Primary Permanency Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoption by a non-relative</fullName>
                <default>true</default>
                <label>Adoption by a non-relative</label>
            </value>
            <value>
                <fullName>Adoption by a relative</fullName>
            </value>
            <value>
                <fullName>APPLA</fullName>
            </value>
            <value>
                <fullName>Guardianship by a non-relative</fullName>
            </value>
            <value>
                <fullName>Guardianship by a relative</fullName>
            </value>
            <value>
                <fullName>Reunification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permanency_Plan__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Permanency Plans</relationshipLabel>
    <relationshipName>Permanency_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Service_Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Case__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Exit_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Exit_Approval_Status__c</fullName>
    <label>Exit Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Placement_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Approval_Status__c</fullName>
    <label>Placement Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Concurrent_Comments__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Concurrent_Permanency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Permanency_Plan__c</fullName>
    <label>Concurrent Permanency Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Concurrent_Plan_Established_Date__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Plan_Established_Date__c</fullName>
    <label>Plan Established Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Plan_Established_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Established_Date__c</fullName>
    <label>Plan Established Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/fields/Primary_Permanency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Primary_Permanency_Plan__c</fullName>
    <label>Primary Permanency Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PermanacyPlanController.cls
public with sharing class PermanacyPlanController {
    
    @AuraEnabled
    public static String getInitialInformation(String serviceCaseRecordId, String permanencyPlanRecordId) {  
        getInitialWrapper initWrap = new getInitialWrapper();
        initWrap.primaryPicklist = Utility.getPicklistinfo('Permanency_Plan__c','Primary_Permanency_Plan__c',false);
        initWrap.concurrentPicklist = Utility.getPicklistinfo('Permanency_Plan__c','Concurrent_Permanency_Plan__c',false);
        initWrap.returnPicklist = Utility.getPicklistinfo('Permanency_Plan__c','If_the_Permanency_plan_is_to_return_home__c',false);
        initWrap.guardianshipPlaningPicklist = Utility.getPicklistinfo('Permanency_Plan__c','Guardianship_Planing__c',false);
        FieldLevelSecurity.checkFieldAccessByCriteria('Service_Case__c,Child__c, Exit_Approval_Status__c', 'view', 'Placement__c',  Boolean.valueOf(Label.HasNamespace));
        FieldLevelSecurity.checkFieldAccessByCriteria('Name,Intake_Person_Role__c,Age__c,Date_of_Birth__c', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));
        
        initWrap.approvedPlacementChildList = [SELECT Service_Case__c, Id, Child__c, Child__r.Name, Child__r.Intake_Person_Role__c, Child__r.Age__c, Child__r.Date_of_Birth__c, Exit_Approval_Status__c FROM Placement__c 
                                     WHERE Child__c != Null AND Placement_Approval_Status__c = 'Approved'
                                     AND Service_Case__c = :serviceCaseRecordId AND 
                                     Exit_Approval_Status__c != 'Approved' AND End_Date__c = null ORDER BY lastModifiedDate  DESC LIMIT :Utility.queryLimit];
        
        if(String.isNotBlank(permanencyPlanRecordId)){
        FieldLevelSecurity.checkFieldAccessByCriteria('Primary_Permanency_Plan__c, Plan_Established_Date__c, Plan_Comments__c, Concurrent_Permanency_Plan__c, Concurrent_Plan_Established_Date__c, Concurrent_Comments__c, End_Date__c, End_Reason__c, Court_order_received_and_upload_in_CJAMS__c, If_the_Permanency_plan_is_to_return_home__c, Explanation_Required__c,Discuss_how_the_caregiver_is_meeting__c, Discuss_and_explain_changes_in_the_child__c, Describe_how_the_worker_is_carrying_out__c, Document_what_steps_have_been_taken__c,Describe_how_the_worker_is_ensuring__c,What_efforts_were_made_to_promote__c,Has_a_Lifebook_been_prepared__c,Describe_the_parent_s_compliance__c,Does_the_Provider_agree_permanency__c,Permanancy_Agree_Explanation_Required__c,Discuss_services_being_provided__c,Contact__c', 'view', 'Permanency_Plan__c',  Boolean.valueOf(Label.HasNamespace));
        initWrap.permanencyInst = [SELECT Id, Primary_Permanency_Plan__c, Plan_Established_Date__c, Plan_Comments__c, Concurrent_Permanency_Plan__c,
                                   Concurrent_Plan_Established_Date__c, Concurrent_Comments__c, End_Date__c, End_Reason__c, 
                                   Court_order_received_and_upload_in_CJAMS__c, If_the_Permanency_plan_is_to_return_home__c,
                                   Explanation_Required__c,Discuss_how_the_caregiver_is_meeting__c, Discuss_and_explain_changes_in_the_child__c,
                                   Describe_how_the_worker_is_carrying_out__c, Document_what_steps_have_been_taken__c, Describe_how_the_worker_is_ensuring__c,
                                   What_efforts_were_made_to_promote__c, Has_a_Lifebook_been_prepared__c, Describe_the_parent_s_compliance__c, 
                                   Does_the_Provider_agree_permanency__c, Permanancy_Agree_Explanation_Required__c, Discuss_services_being_provided__c, 
                                   Contact__c FROM Permanency_Plan__c WHERE Id = :permanencyPlanRecordId LIMIT :Utility.queryLimit];
        }                          
       return JSON.serialize(initWrap);
    }
   
    @AuraEnabled
    public static String createPermanancyPlan(String permanancyDataJSON) {
    
       if (String.isNotBlank(permanancyDataJSON)) {
           Permanency_Plan__c createPermanacyRec = (Permanency_Plan__c) JSON.deserialize(permanancyDataJSON, Permanency_Plan__c.class);
           if (String.isBlank(createPermanacyRec.Id)) {
               
               FieldLevelSecurity.checkFieldAccessByCriteria('Name,Primary_Permanency_Plan__c,Plan_Established_Date__c,Plan_Comments__c,Concurrent_Permanency_Plan__c,Concurrent_Plan_Established_Date__c,'+
                                                      'Concurrent_Comments__c,End_Date__c,End_Reason__c,Court_order_received_and_upload_in_CJAMS__c,If_the_Permanency_plan_is_to_return_home__c,Explanation_Required__c,'+
                                                      'Discuss_how_the_caregiver_is_meeting__c,Discuss_and_explain_changes_in_the_child__c,Describe_how_the_worker_is_carrying_out__c,Document_what_steps_have_been_taken__c,Describe_how_the_worker_is_ensuring__c,'+
                                                      'What_efforts_were_made_to_promote__c,Has_a_Lifebook_been_prepared__c,Describe_the_parent_s_compliance__c,Does_the_Provider_agree_permanency__c,Permanancy_Agree_Explanation_Required__c,Discuss_services_being_provided__c', 'create', 'Permanency_Plan__c',  Boolean.valueOf(Label.HasNamespace));
               insert createPermanacyRec;             
           } else {
               FieldLevelSecurity.checkFieldAccessByCriteria('Name,Primary_Permanency_Plan__c,Plan_Established_Date__c,Plan_Comments__c,Concurrent_Permanency_Plan__c,Concurrent_Plan_Established_Date__c,'+
                                                      'Concurrent_Comments__c,End_Date__c,End_Reason__c,Court_order_received_and_upload_in_CJAMS__c,If_the_Permanency_plan_is_to_return_home__c,Explanation_Required__c,'+
                                                      'Discuss_how_the_caregiver_is_meeting__c,Discuss_and_explain_changes_in_the_child__c,Describe_how_the_worker_is_carrying_out__c,Document_what_steps_have_been_taken__c,Describe_how_the_worker_is_ensuring__c,'+
                                                      'What_efforts_were_made_to_promote__c,Has_a_Lifebook_been_prepared__c,Describe_the_parent_s_compliance__c,Does_the_Provider_agree_permanency__c,Permanancy_Agree_Explanation_Required__c,Discuss_services_being_provided__c', 'update', 'Permanency_Plan__c',  Boolean.valueOf(Label.HasNamespace));
              update createPermanacyRec;
           
           }
           return createPermanacyRec.Id;
       } else {
           return null;
       }         
         
    }
    
    
    public class getInitialWrapper { 
        @AuraEnabled
        public List<Utility.pickListWrap> primaryPicklist;
        @AuraEnabled
        public List<Utility.pickListWrap> concurrentPicklist;
        @AuraEnabled
        public List<Utility.pickListWrap> returnPicklist;
        @AuraEnabled
        public List<Utility.pickListWrap> guardianshipPlaningPicklist;
        @AuraEnabled
        public Permanency_Plan__c  permanencyInst;
        @AuraEnabled
        public List<contact>  childList;
        @AuraEnabled
        public Permanency_Plan__c  permanencyInitialInst;
        @AuraEnabled
        public Placement__c placementRecId;
        @AuraEnabled
        public List<Placement__c> approvedPlacementChildList;
        
    }
    
    @AuraEnabled
    public static String getInitialPermanancyDetails(String permanancyPlanId) {  
    
        getInitialWrapper initWrap = new getInitialWrapper();
        initWrap.guardianshipPlaningPicklist = Utility.getPicklistinfo('Permanency_Plan__c','Guardianship_Planing__c',false);
        FieldLevelSecurity.checkFieldAccessByCriteria('Guardianship_Planing__c, Gender__c, D_O_B__c, Client_Name__c, Contact__c', 'view','Permanency_Plan__c' ,  Boolean.valueOf(Label.HasNamespace));
        initWrap.permanencyInst = [SELECT Id, Guardianship_Planing__c, Gender__c, D_O_B__c, Client_Name__c,
                                   Contact__r.Casevault_PID__c FROM Permanency_Plan__c WHERE Id = :permanancyPlanId LIMIT :Utility.queryLimit];
        
        return JSON.serialize(initWrap);
    }


}